-- Enable UUID generation
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- =========================================================
-- USERS
-- Authentication and identity for patients/caregivers/admins
-- =========================================================

CREATE TYPE user_role AS ENUM (
    'patient',
    'caregiver',
    'admin'
);

CREATE TABLE users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    name VARCHAR(100) NOT NULL,

    email VARCHAR(255) NOT NULL UNIQUE,

    password_hash TEXT NOT NULL,

    role user_role NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- =========================================================
-- PATIENTS
-- Patient-specific information
-- =========================================================

CREATE TABLE patients (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    user_id UUID NOT NULL UNIQUE
        REFERENCES users(id) ON DELETE CASCADE,

    date_of_birth DATE,

    emergency_notes TEXT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- =========================================================
-- PATIENT ↔ CAREGIVER
-- Many-to-many relationship
-- =========================================================

CREATE TABLE patient_caregiver (
    patient_id UUID NOT NULL
        REFERENCES patients(id) ON DELETE CASCADE,

    caregiver_id UUID NOT NULL
        REFERENCES users(id) ON DELETE CASCADE,

    relationship_type VARCHAR(50),

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    PRIMARY KEY (patient_id, caregiver_id)
);


-- =========================================================
-- SAFE ZONES
-- Circular geographic regions around a patient
-- =========================================================

CREATE TABLE safe_zones (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    patient_id UUID NOT NULL
        REFERENCES patients(id) ON DELETE CASCADE,

    name VARCHAR(100) NOT NULL,

    center GEOGRAPHY(POINT, 4326) NOT NULL,

    radius_meters DOUBLE PRECISION NOT NULL
        CHECK (radius_meters > 0),

    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_safe_zones_patient
    ON safe_zones(patient_id);

CREATE INDEX idx_safe_zones_center
    ON safe_zones USING GIST(center);


-- =========================================================
-- LOCATIONS
-- Patient location history
-- =========================================================

CREATE TABLE locations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    patient_id UUID NOT NULL
        REFERENCES patients(id) ON DELETE CASCADE,

    location GEOGRAPHY(POINT, 4326) NOT NULL,

    accuracy_meters DOUBLE PRECISION,

    recorded_at TIMESTAMPTZ NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_locations_patient_time
    ON locations(patient_id, recorded_at DESC);

CREATE INDEX idx_locations_location
    ON locations USING GIST(location);


-- =========================================================
-- DEVICES
-- Devices used by patients for location tracking
-- =========================================================

CREATE TABLE devices (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    patient_id UUID NOT NULL
        REFERENCES patients(id) ON DELETE CASCADE,

    device_identifier VARCHAR(255) NOT NULL UNIQUE,

    platform VARCHAR(20) NOT NULL,

    last_seen_at TIMESTAMPTZ,

    battery_percent INTEGER
        CHECK (battery_percent BETWEEN 0 AND 100),

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_devices_patient
    ON devices(patient_id);


-- =========================================================
-- ALERTS
-- Safety incidents generated by the system
-- =========================================================

CREATE TYPE alert_type AS ENUM (
    'left_safe_zone',
    'sos',
    'device_offline'
);

CREATE TYPE alert_status AS ENUM (
    'active',
    'acknowledged',
    'resolved'
);

CREATE TABLE alerts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    patient_id UUID NOT NULL
        REFERENCES patients(id) ON DELETE CASCADE,

    safe_zone_id UUID
        REFERENCES safe_zones(id) ON DELETE SET NULL,

    type alert_type NOT NULL,

    status alert_status NOT NULL DEFAULT 'active',

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    acknowledged_at TIMESTAMPTZ,

    resolved_at TIMESTAMPTZ
);

CREATE INDEX idx_alerts_patient_status
    ON alerts(patient_id, status);

CREATE INDEX idx_alerts_created_at
    ON alerts(created_at DESC);


-- =========================================================
-- NOTIFICATIONS
-- Tracks notification delivery separately from alerts
-- =========================================================

CREATE TYPE notification_channel AS ENUM (
    'push'
);

CREATE TYPE notification_status AS ENUM (
    'pending',
    'sent',
    'failed'
);

CREATE TABLE notifications (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    alert_id UUID NOT NULL
        REFERENCES alerts(id) ON DELETE CASCADE,

    recipient_id UUID NOT NULL
        REFERENCES users(id) ON DELETE CASCADE,

    channel notification_channel NOT NULL,

    status notification_status NOT NULL DEFAULT 'pending',

    sent_at TIMESTAMPTZ,

    delivered_at TIMESTAMPTZ,

    failure_reason TEXT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_notifications_alert
    ON notifications(alert_id);

CREATE INDEX idx_notifications_recipient
    ON notifications(recipient_id);